stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: kirito
  IMAGE_TAG: latest

# -------------------
# TEST STAGE
# -------------------
test:
  stage: test
  image: golang:1.24
  script:
    - go version
    - go mod tidy
    - go test ./...

# -------------------
# BUILD STAGE
# -------------------
build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
  only:
    - main

# -------------------
# DEPLOY STAGE
# -------------------
deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - echo "Preparing kubeconfig"
    - mkdir -p ~/.kube
    - cp kubeconfig_dummy.yaml ~/.kube/config

    - echo "Kubectl client check"
    - kubectl version --client

    - echo "Simulating deployment (no real cluster)"
    - kubectl apply -f k8s/ || echo "Cluster not reachable (expected in test)"
